project:
  type: website
  output-dir: docs
website:
  title: "AISES UCSB"
  favicon: images/favicon.png
  search: false
  navbar:
    title: false
    logo: images/logo.png
    pinned: true
    right:
      - text: About
        href: index.qmd
format:
  html:
    theme:
      - styles.scss
    mainfont: IBM Plex Sans
    page-layout: full
    link-external-newwindow: true
    toc: false